// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: redeemable/v1/redeemable_service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RedeemableServiceClient is the client API for RedeemableService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RedeemableServiceClient interface {
	RedeemToken(ctx context.Context, in *RedeemTokenRequest, opts ...grpc.CallOption) (*RedeemTokenResponse, error)
	ResetToken(ctx context.Context, in *ResetTokenRequest, opts ...grpc.CallOption) (*ResetTokenResponse, error)
}

type redeemableServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRedeemableServiceClient(cc grpc.ClientConnInterface) RedeemableServiceClient {
	return &redeemableServiceClient{cc}
}

func (c *redeemableServiceClient) RedeemToken(ctx context.Context, in *RedeemTokenRequest, opts ...grpc.CallOption) (*RedeemTokenResponse, error) {
	out := new(RedeemTokenResponse)
	err := c.cc.Invoke(ctx, "/redeemable.v1.RedeemableService/RedeemToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redeemableServiceClient) ResetToken(ctx context.Context, in *ResetTokenRequest, opts ...grpc.CallOption) (*ResetTokenResponse, error) {
	out := new(ResetTokenResponse)
	err := c.cc.Invoke(ctx, "/redeemable.v1.RedeemableService/ResetToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RedeemableServiceServer is the server API for RedeemableService service.
// All implementations must embed UnimplementedRedeemableServiceServer
// for forward compatibility
type RedeemableServiceServer interface {
	RedeemToken(context.Context, *RedeemTokenRequest) (*RedeemTokenResponse, error)
	ResetToken(context.Context, *ResetTokenRequest) (*ResetTokenResponse, error)
	mustEmbedUnimplementedRedeemableServiceServer()
}

// UnimplementedRedeemableServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRedeemableServiceServer struct {
}

func (UnimplementedRedeemableServiceServer) RedeemToken(context.Context, *RedeemTokenRequest) (*RedeemTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RedeemToken not implemented")
}
func (UnimplementedRedeemableServiceServer) ResetToken(context.Context, *ResetTokenRequest) (*ResetTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetToken not implemented")
}
func (UnimplementedRedeemableServiceServer) mustEmbedUnimplementedRedeemableServiceServer() {}

// UnsafeRedeemableServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RedeemableServiceServer will
// result in compilation errors.
type UnsafeRedeemableServiceServer interface {
	mustEmbedUnimplementedRedeemableServiceServer()
}

func RegisterRedeemableServiceServer(s grpc.ServiceRegistrar, srv RedeemableServiceServer) {
	s.RegisterService(&RedeemableService_ServiceDesc, srv)
}

func _RedeemableService_RedeemToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedeemTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedeemableServiceServer).RedeemToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/redeemable.v1.RedeemableService/RedeemToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedeemableServiceServer).RedeemToken(ctx, req.(*RedeemTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedeemableService_ResetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedeemableServiceServer).ResetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/redeemable.v1.RedeemableService/ResetToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedeemableServiceServer).ResetToken(ctx, req.(*ResetTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RedeemableService_ServiceDesc is the grpc.ServiceDesc for RedeemableService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RedeemableService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "redeemable.v1.RedeemableService",
	HandlerType: (*RedeemableServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RedeemToken",
			Handler:    _RedeemableService_RedeemToken_Handler,
		},
		{
			MethodName: "ResetToken",
			Handler:    _RedeemableService_ResetToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "redeemable/v1/redeemable_service.proto",
}
