// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: orders/v1/fees.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//
	//	*ListRequest_OrderId
	//	*ListRequest_TicketId
	Type isListRequest_Type `protobuf_oneof:"type"`
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orders_v1_fees_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_v1_fees_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_orders_v1_fees_proto_rawDescGZIP(), []int{0}
}

func (m *ListRequest) GetType() isListRequest_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *ListRequest) GetOrderId() string {
	if x, ok := x.GetType().(*ListRequest_OrderId); ok {
		return x.OrderId
	}
	return ""
}

func (x *ListRequest) GetTicketId() string {
	if x, ok := x.GetType().(*ListRequest_TicketId); ok {
		return x.TicketId
	}
	return ""
}

type isListRequest_Type interface {
	isListRequest_Type()
}

type ListRequest_OrderId struct {
	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3,oneof"`
}

type ListRequest_TicketId struct {
	TicketId string `protobuf:"bytes,2,opt,name=ticket_id,json=ticketId,proto3,oneof"`
}

func (*ListRequest_OrderId) isListRequest_Type() {}

func (*ListRequest_TicketId) isListRequest_Type() {}

type ListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fees []*Fee `protobuf:"bytes,1,rep,name=fees,proto3" json:"fees,omitempty"`
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orders_v1_fees_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_v1_fees_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_orders_v1_fees_proto_rawDescGZIP(), []int{1}
}

func (x *ListResponse) GetFees() []*Fee {
	if x != nil {
		return x.Fees
	}
	return nil
}

var File_orders_v1_fees_proto protoreflect.FileDescriptor

var file_orders_v1_fees_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x65, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x76,
	0x31, 0x1a, 0x15, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x51, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x09, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x74, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x49, 0x64, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x32, 0x0a, 0x0c, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x66,
	0x65, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x65, 0x65, 0x52, 0x04, 0x66, 0x65, 0x65, 0x73, 0x32,
	0x47, 0x0a, 0x0a, 0x46, 0x65, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a,
	0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x97, 0x01, 0x0a, 0x1a, 0x63, 0x6f, 0x6d,
	0x2e, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x42, 0x09, 0x46, 0x65, 0x65, 0x73, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x01, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x75, 0x6e, 0x69, 0x69, 0x76, 0x65, 0x72, 0x73, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73,
	0x72, 0x63, 0x2f, 0x67, 0x6f, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x2f, 0x76, 0x31, 0xa2,
	0x02, 0x03, 0x4f, 0x58, 0x58, 0xaa, 0x02, 0x09, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x56,
	0x31, 0xca, 0x02, 0x09, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x15,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0a, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x3a, 0x3a,
	0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_orders_v1_fees_proto_rawDescOnce sync.Once
	file_orders_v1_fees_proto_rawDescData = file_orders_v1_fees_proto_rawDesc
)

func file_orders_v1_fees_proto_rawDescGZIP() []byte {
	file_orders_v1_fees_proto_rawDescOnce.Do(func() {
		file_orders_v1_fees_proto_rawDescData = protoimpl.X.CompressGZIP(file_orders_v1_fees_proto_rawDescData)
	})
	return file_orders_v1_fees_proto_rawDescData
}

var file_orders_v1_fees_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_orders_v1_fees_proto_goTypes = []interface{}{
	(*ListRequest)(nil),  // 0: orders.v1.ListRequest
	(*ListResponse)(nil), // 1: orders.v1.ListResponse
	(*Fee)(nil),          // 2: orders.v1.Fee
}
var file_orders_v1_fees_proto_depIdxs = []int32{
	2, // 0: orders.v1.ListResponse.fees:type_name -> orders.v1.Fee
	0, // 1: orders.v1.FeeService.List:input_type -> orders.v1.ListRequest
	1, // 2: orders.v1.FeeService.List:output_type -> orders.v1.ListResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_orders_v1_fees_proto_init() }
func file_orders_v1_fees_proto_init() {
	if File_orders_v1_fees_proto != nil {
		return
	}
	file_orders_v1_types_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_orders_v1_fees_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orders_v1_fees_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_orders_v1_fees_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ListRequest_OrderId)(nil),
		(*ListRequest_TicketId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_orders_v1_fees_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orders_v1_fees_proto_goTypes,
		DependencyIndexes: file_orders_v1_fees_proto_depIdxs,
		MessageInfos:      file_orders_v1_fees_proto_msgTypes,
	}.Build()
	File_orders_v1_fees_proto = out.File
	file_orders_v1_fees_proto_rawDesc = nil
	file_orders_v1_fees_proto_goTypes = nil
	file_orders_v1_fees_proto_depIdxs = nil
}
