// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: inventory/v1/inventory_service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InventoryServiceClient is the client API for InventoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InventoryServiceClient interface {
	// Return the capacities for a specific listing, along with day-aggregated counts
	Month(ctx context.Context, in *InventoryServiceMonthRequest, opts ...grpc.CallOption) (*InventoryServiceMonthResponse, error)
	// Return all timeslots for a specific date
	Date(ctx context.Context, in *InventoryServiceDateRequest, opts ...grpc.CallOption) (*InventoryServiceDateResponse, error)
	// Return capacities for each applicable inventory type of a single event(timeslot)
	Timeslot(ctx context.Context, in *InventoryServiceTimeslotRequest, opts ...grpc.CallOption) (*InventoryServiceTimeslotResponse, error)
}

type inventoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryServiceClient(cc grpc.ClientConnInterface) InventoryServiceClient {
	return &inventoryServiceClient{cc}
}

func (c *inventoryServiceClient) Month(ctx context.Context, in *InventoryServiceMonthRequest, opts ...grpc.CallOption) (*InventoryServiceMonthResponse, error) {
	out := new(InventoryServiceMonthResponse)
	err := c.cc.Invoke(ctx, "/inventory.v1.InventoryService/Month", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) Date(ctx context.Context, in *InventoryServiceDateRequest, opts ...grpc.CallOption) (*InventoryServiceDateResponse, error) {
	out := new(InventoryServiceDateResponse)
	err := c.cc.Invoke(ctx, "/inventory.v1.InventoryService/Date", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) Timeslot(ctx context.Context, in *InventoryServiceTimeslotRequest, opts ...grpc.CallOption) (*InventoryServiceTimeslotResponse, error) {
	out := new(InventoryServiceTimeslotResponse)
	err := c.cc.Invoke(ctx, "/inventory.v1.InventoryService/Timeslot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryServiceServer is the server API for InventoryService service.
// All implementations must embed UnimplementedInventoryServiceServer
// for forward compatibility
type InventoryServiceServer interface {
	// Return the capacities for a specific listing, along with day-aggregated counts
	Month(context.Context, *InventoryServiceMonthRequest) (*InventoryServiceMonthResponse, error)
	// Return all timeslots for a specific date
	Date(context.Context, *InventoryServiceDateRequest) (*InventoryServiceDateResponse, error)
	// Return capacities for each applicable inventory type of a single event(timeslot)
	Timeslot(context.Context, *InventoryServiceTimeslotRequest) (*InventoryServiceTimeslotResponse, error)
	mustEmbedUnimplementedInventoryServiceServer()
}

// UnimplementedInventoryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedInventoryServiceServer struct {
}

func (UnimplementedInventoryServiceServer) Month(context.Context, *InventoryServiceMonthRequest) (*InventoryServiceMonthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Month not implemented")
}
func (UnimplementedInventoryServiceServer) Date(context.Context, *InventoryServiceDateRequest) (*InventoryServiceDateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Date not implemented")
}
func (UnimplementedInventoryServiceServer) Timeslot(context.Context, *InventoryServiceTimeslotRequest) (*InventoryServiceTimeslotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Timeslot not implemented")
}
func (UnimplementedInventoryServiceServer) mustEmbedUnimplementedInventoryServiceServer() {}

// UnsafeInventoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryServiceServer will
// result in compilation errors.
type UnsafeInventoryServiceServer interface {
	mustEmbedUnimplementedInventoryServiceServer()
}

func RegisterInventoryServiceServer(s grpc.ServiceRegistrar, srv InventoryServiceServer) {
	s.RegisterService(&InventoryService_ServiceDesc, srv)
}

func _InventoryService_Month_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InventoryServiceMonthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).Month(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inventory.v1.InventoryService/Month",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).Month(ctx, req.(*InventoryServiceMonthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_Date_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InventoryServiceDateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).Date(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inventory.v1.InventoryService/Date",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).Date(ctx, req.(*InventoryServiceDateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_Timeslot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InventoryServiceTimeslotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).Timeslot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inventory.v1.InventoryService/Timeslot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).Timeslot(ctx, req.(*InventoryServiceTimeslotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryService_ServiceDesc is the grpc.ServiceDesc for InventoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.v1.InventoryService",
	HandlerType: (*InventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Month",
			Handler:    _InventoryService_Month_Handler,
		},
		{
			MethodName: "Date",
			Handler:    _InventoryService_Date_Handler,
		},
		{
			MethodName: "Timeslot",
			Handler:    _InventoryService_Timeslot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inventory/v1/inventory_service.proto",
}
