name: Release Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}

jobs:
  semantic-release:
    permissions:
      contents: write
      id-token: write
    uses: uniiverse/workflows/.github/workflows/semantic-release-npm.yaml@main
    secrets: inherit